- README.md
> 一番最初に誰が始めた物語なのか明示する必要があります。

- README.md
> Add brain-yasu**ri

- README.md
> fix: change the title of brain-yasu**ri

- README.md
> fix: change the date in the table

- README.md
- yasunori.toml
軽微すぎて2つに分けるのが面倒くさかったから一つにまとめて送ります。
もともとは
https://github.com/takeokunn/awesome-yasunori/blob/f40f05deb7213d68b5c8de2fc1c1337d41150347/README.md?plain=1#L210-L222
のようにTwitterのリンクが上にありましたが多分readmegenでその配置ができないため移動しています
> 軽微な修正(メタを追加/曜日を修正)

- README.md
- yasunori.toml
> Add id number

- .github/workflows/deploy.yml
- packages/api/.npmrc
- packages/api/package.json
> yasunori API を GithubActions からデプロイする

- .github/workflows/ci.yml
- packages/api/package.json
- packages/api/pnpm-lock.yaml
- packages/api/src/get-parsed-awesome-yasunori.ts
- packages/api/src/index.test.ts
- packages/api/vite.config.ts
Close #15
テストコードを先に追加して、id の追加をコミットレベルで確認できるようにしました。
なので、実装としては b2a1e39 こちらのコミットだけになります。
> id を APIレスポンスに追加する

- .github/workflows/ci.yml
- packages/api/biome.json
- packages/api/package.json
- packages/api/pnpm-lock.yaml
- packages/api/src/index.test.ts
- packages/api/tsconfig.json
- typecheck コマンドを追加
- CI で typecheck, lint, format のチェックを実施
> CIで lint, typecheck, format チェックを実施する

- packages/api/README.md
- packages/api/package.json
README をちゃんとしました。
あと、念のため package.json に license などの情報を追加しました。
> APIパッケージのREADMEとpackage.jsonの更新

- .github/workflows/ci.yml
- schema.json
Awesome yasunori 専用の JSON Schema を作成しました。
これを利用して toml を JSON 変換した上で、スキーマバリデーションを実行する CI ジョブを追加しました。
問題なければ [JSON Schema Store](https://www.schemastore.org/) に登録しようと思います。
> Awesome yasunori JSON Schema の作成

- .github/workflows/deploy.yml
- packages/web/app/root.tsx
useMediaQuery 判定に px を指定すると実際の判定とずれるため、em を利用して計算させるようにする。
> useMediaQuery の計算に px ではなく em 換算の数値を利用する

- packages/web/app/hooks/use-awsome-yasunori.ts
- packages/web/app/root.tsx
- packages/web/app/routes/_index/loader.ts
- packages/web/app/routes/feed[.xml].tsx
- packages/web/app/shared/fetch-awsome-yasunori.ts
- packages/web/package.json
- packages/web/pnpm-lock.yaml
- RSS Feedを追加. https://awsome.yasunori.dev/feed.xml
- NavBarにRSS Iconの追加
> RSS Feedの追加

- .github/workflows/ci.yml
> GitHub Actions の名前を整理

- README.md
- packages/api/src/index.test.ts
- packages/api/src/index.ts
- packages/web/README.md
- org 移行に関する修正
- web の SPA -> SSR 移行に関する修正
> README の修正漏れ（主に org 移行に関するもの）対応

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .gitignore
- .npmrc
- package.json
- packages/api/package.json
- packages/web/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
pnpm monorepoにします
web系のものはroot dirからコマンドで一発で走るようにします
fixes: https://github.com/times-yasunori/awesome-yasunori/issues/34
> pnpm monorepo

- packages/api/src/index.ts
- packages/web/app/shared/fetch-awesome-yasunori.ts
- packages/web/app/shared/yasunori-api.ts
- packages/web/package.json
- pnpm-lock.yaml
hono rpcで通信を型安全に
https://hono.dev/docs/guides/rpc
> use Hono RPC to get type-safe response from yasunori api

- packages/web/app/routes/feed[.xml].tsx
> fix rss feed content

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
> husky + lint-staged を使って pre-commit で biome check --write をかける

- yasunori.toml
> Modify yasunori github id

- yasunori.toml
Close: https://github.com/times-yasunori/awesome-yasunori/issues/53
> Modify kuu github id

- packages/web/app/root.tsx
> サイトタイトルをオシャレに

- packages/web/public/_headers
This code is here from template
> Remove /assets/* Cache-Control headers

- packages/web/wrangler.toml
Ref  #61
1. 新規プロジェクトとしてデプロイする
2. CNAME を変更する
を試してみる。
> キャッシュ問題の解決のため、Cloundflare Pages に新規プロジェクトとしてデプロイする

- packages/web/app/root.tsx
- packages/web/package.json
- pnpm-lock.yaml
> feat(packages/web): add GitHub repository link with octcat icon

- packages/web/app/root.tsx
- packages/web/app/routes/_index/route.tsx
- packages/web/package.json
- pnpm-lock.yaml
IconをTablerに物に置き換える
https://icones.js.org/collection/tabler
置き換え後のpreview
https://github.com/user-attachments/assets/dbe9cdee-692d-429b-ab82-e1d3c9444fa4
> feat(package/web): replace all icons from tabler

- packages/web/app/routes/feed[.xml].tsx
https://github.com/times-yasunori/awesome-yasunori/pull/66 を受けて、RSSで表示するlinkを修正
> fix rss link

- packages/web/app/routes/_index/route.tsx
- packages/web/app/routes/entries.$id/route.tsx
- #50
こちらの下準備として meta に情報を追加する。
```
<title>Awesome Yasunori</title>
<meta name="description" content="Welcome to awesome yasunori!"/>
<meta property="og:url" content="https://awesome.yasunori.dev"/>
<meta property="og:site_name" content="Awesome Yasunori"/>
<meta property="og:title" content="Awesome Yasunori"/>
<meta property="og:description" content="Welcome to awesome yasunori!"/>
<meta property="og:locale" content="ja"/>
<meta property="og:type" content="website"/>
```
```
<title>yasunoriは勉強になる</title>
<meta name="description" content="yasunori のおかげで JSON Schema を初めて作ったし、yasunori は勉強になる"/>
<meta property="og:url" content="https://awesome.yasunori.dev/entries/29"/>
<meta property="og:site_name" content="Awesome Ysunori"/>
<meta property="og:title" content="yasunoriは勉強になる"/>
<meta …
```
> OGP 画像以外の OGP 情報を挿入する

- packages/api/src/get-parsed-request-params.ts
- packages/api/src/index.test.ts
- packages/api/src/index.ts
> GET /awesome/:id エンドポイントの追加

- package.json
- packages/api/package.json
- packages/web/package.json
- pnpm-lock.yaml
Add specific package commands to npm scripts. and use specific port on dev servers.
> Improve npm scripts and set specific port to dev server

- .github/workflows/deploy.yml
- README.md
- biome.json
- packages/image-generator/.gitignore
- packages/image-generator/.npmrc
- packages/image-generator/REAME.md
- packages/image-generator/functions/ogp/index.tsx
- packages/image-generator/package.json
- packages/image-generator/tsconfig.json
- packages/image-generator/wrangler.toml
- packages/web/app/routes/entries.$id/route.tsx
- pnpm-lock.yaml
@cloudflare/pages-plugin-vercel-og を使って、Cloundflare Pages Functions で動く、画像ジェネレーターアプリケーションを作成しました。
まだ、キャッシュは導入していないため、負荷が高まると落ちる可能性があります。
meta タグの挿入は行ったので、マージ後に web でカードが期待通り表示されるか確認する必要があります。
> Awesome Yasunori Image Generator

- packages/image-generator/functions/ogp/index.tsx
cache機能を設定しました。
- cacheの有効期限は1日としていますが、変更化です	
関連: https://github.com/times-yasunori/awesome-yasunori/pull/87
> feat(image-generator): implement cache

- packages/image-generator/functions/ogp/index.tsx
Close #99
取得したAPIリソースのURLを元にキャッシュキーを作成するように変更しました。
元の実装に比べてAPIのリクエストが増えるかたちになりましたが、トレードオフであることと、そこはそこまで重くないので、許容範囲だと思います。
> /ogp の画像をキャッシュで固定されないようにする

- packages/web/app/root.tsx
> ヘッダーにあるアイコンを大きくして離す

- .github/workflows/ci.yml
Close #108
フォークプルリクエストでもCIが回るようにする
> Fix CI trigger for forked pull-request

- .github/workflows/ci.yml
- README.md
- nix/default.nix
- nix/packages/default.nix
- nix/packages/yasunori-net/default.nix
- nix/packages/yasunori-net/deps.nix
- nix/shells/default.nix
`Yasunori.NET`をNixでビルドしました
`nix run github://times-yasunori/awesome-yasunori#yasunori-net`で実行できるようになります
cc @teramako
> nix: build and cache Yasunori.Net

- packages/web/app/routes/entries.$id/loader.test.ts
- packages/web/app/routes/entries.$id/loader.ts
- packages/web/app/shared/fetch-awesome-yasunori-entry.ts
- packages/web/mocks/server/handlers.ts
- packages/web/mocks/server/index.ts
> 単体表示ページは、単体取得APIを利用するようにリファクタリング

- packages/web/app/components/yasunori-spotlight/index.tsx
- packages/web/app/root.tsx
- packages/web/package.json
- pnpm-lock.yaml
Close #80
UIとしてこうなるという例があったほうが改良しやすいと思ったので、ベストではないですがとりあえず検索機能をつけました。
PC
スマホ
> Awesome Yasunori 検索

- biome.json
- packages/web/app/root.tsx
- packages/web/app/routes/stats/aggregate.ts
- packages/web/app/routes/stats/route.tsx
- packages/web/package.json
- pnpm-lock.yaml
stats ページを実装。あと、なんとなくタイトルフォントを変更しました。
> Awesome Yasunori Stats

- packages/web/app/root.tsx
- packages/web/app/routes/stats/aggregate.test.ts
- packages/web/app/routes/stats/aggregate.ts
- packages/web/app/routes/stats/route.tsx
> Awesome Yasunori Stats に Senpan Ranking を追加

- .github/workflows/ci.yml
- flake.lock
- flake.nix
- nix/packages/default.nix
- nix/packages/yasunori-cli/default.nix
https://github.com/times-yasunori/kuusay/blob/4c9d6b7b9d496aa813661c535142206955491063/packages/yasunori-cli/default.nix を移動してきました。
ついでに `nix run` できるようにしてます。
`/nix/packages/yasunori-cli` に置いたけど、置き場ここでいい？
> feat(nix): add yasunori-cli from times-yasunori/kuusay

- packages/web/app/root.tsx
- packages/web/package.json
- pnpm-lock.yaml
Awesome Yasunori の Yasunori を一定間隔で yasunori するようにしました。
https://github.com/user-attachments/assets/4b94ebb7-af47-4752-8078-2777b8847c63
> Yasunorized  Yasunori

- packages/web/app/components/awesome-yasunori-card/index.tsx
試しに Share Button に Web Share API を使ってみました。
> Use Web Share API instead of CopyButton

- yasunori.toml
> Add 最新技術がこんなことに使われているなんて

- packages/go-yasunori/.gitignore
- packages/go-yasunori/README.md
- packages/go-yasunori/go.mod
- packages/go-yasunori/main.go
> Add go-yasunori

- yasunori.toml
> Add: AIに生成された次回予告

- yasunori.toml
> 新たなyasunoriを追加

- yasunori.toml
> :tada: (yasunori.toml) Add new yasunori

- packages/mcp/README.md
- packages/mcp/package.json
- packages/mcp/tsdown.config.ts
> fix(mcp): simplify build script

- yasunori.toml
> Add to yasunori.toml みんなyasunoriしすぎ

- packages/mcp/package.json
- packages/mcp/src/index.ts
- packages/mcp/src/server.test.ts
- pnpm-lock.yaml
In the next version of AY MCP...
We can reference AY from Claude desktop!!!		
Waiting for https://github.com/times-yasunori/awesome-yasunori/pull/183
https://github.com/user-attachments/assets/6937a960-7a9c-461d-97ef-ec40a17b7ca4
> feat(mcp): add resources to AY MCP

- flake.lock
- flake.nix
- nix/overlays.nix
- nix/packages/mcp/default.nix
1. Do `nix flake update`
2. fix pnpm.fetchDeps fails
3. parse package.json at overlay
> Nix flake update

- .github/workflows/ci.yml
> yasunoriは適切に増殖しなければならない

- .github/workflows/cachix.yml
Fix #207
そもそもPRだとCachix ActionのPush動かないっぽいのでPull後に回るようにした
> ci: add cachix push action

- packages/mcp/src/server.test.ts
- packages/mcp/src/server.ts
- mcpにページネーション
- offset/limitがなかったらこれまで通り全部返す
- 全部の長さを返すcoutを実装
> feat(mcp): add pagination support and count tool to MCP server

- packages/mcp/package.json
- packages/mcp/src/index.ts
- packages/mcp/src/schemas.ts
- packages/mcp/src/server.test.ts
- packages/mcp/src/server.ts
- packages/mcp/src/utils.ts
- pnpm-lock.yaml
This PR implements structured output for the MCP (Model Context Protocol) server with proper error handling and improved code organization. The changes include creating a reusable helper function, reorganizing schemas, and ensuring consistent error handling across all MCP tools.
- **Created `createStructuredOutput` helper function** in `utils.ts` - Provides consistent error handling pattern across all MCP tools
- **Organized schemas** - Moved all Zod schemas to dedicated `schemas.ts` file for better separation of concerns
- **Removed YAML dependency** - Completely replaced YAML output with JSON format in resource endpoints
- **Consistent error structure** - All tools now return `{ isError: boolean, result?: T, error?: string }` format
- **Type-safe responses** - Using TypeScript generics …
> refactor(mcp): implement structured output with proper error handling
