times-yasunori/awesome-yasunori

packages/api/.gitignore
packages/api/README.md
packages/api/biome.json
packages/api/package.json
packages/api/pnpm-lock.yaml
packages/api/script/generate-awesome-yasunori-json.js
packages/api/src/get-parsed-awesome-yasunori.ts
packages/api/src/index.ts
packages/api/tsconfig.json
packages/api/vite.config.ts
packages/api/wrangler.toml

api.yasunori.dev として Cloundflare pages にデプロイする API 用のパッケージを作成しました。
https://github.com/yusukebe/ramen-api を参考に実装しています。
下記のエンドポイントで動作確認できます。
- https://create-yasunori-api.yasunori-apis.pages.dev/
- https://create-yasunori-api.yasunori-apis.pages.dev/awesome
1. 最初は、APIサーバー起動時に yasunori.toml をを読み込もうとしたのですが、Cloundflare pages 上で node.js の fs が使えなかったので、ビルド前にあらかじめ json ファイルを生成する形にしました。
2. ドメインは api.awesome.yasunori.dev にしようかと思ったのですが、Cloundflare pages の無料プランだとSSL証明書の発行ができなかったため、 api.yasunori.dev を利用することにしました。
CDは main マージ後に Cloundflare の設定を確認して実施します。

yasunori APIs パッケージの追加

---

packages/web/app/root.tsx

スマホだと Navbar が画面全体を覆っているので遷移したかどうか分からない。
自動的に閉じることで、遷移を視認できるようになる。

モバイルのとき、選択後に Navbar を自動的に閉じる

---

packages/web/app/routes/_index/route.tsx

色の主張を抑えめにして、テキストに被らないようにする。
PC
スマホ

Copy ボタンのスタイルと位置を調整

---

packages/web/app/components/awesome-yasunori-card/index.tsx
packages/web/app/root.tsx
packages/web/app/routes/_index/loader.ts
packages/web/app/routes/_index/route.tsx
packages/web/app/routes/entries.$id/loader.ts
packages/web/app/routes/entries.$id/route.tsx

Close #49
URL は `/:id` だとさすがにネームスペースを汚染しすぎるかと思ったので、 `/entries/:id` にしました。 
タイトル横の `#id` をクリックすると、単体のページへと遷移できます。
単体での表示はドンと目立たせるために中央配置にしています。

単体の  Awesome Yasunori を表示するページを作成

---

.github/workflows/ci.yml
packages/web/app/routes/_index/loader.test.ts
packages/web/app/routes/entries.$id/loader.test.ts
packages/web/mocks/server/handlers.ts
packages/web/mocks/server/index.ts
packages/web/package.json
packages/web/tsconfig.json
packages/web/vite.config.ts
packages/web/vitest.setup.ts
pnpm-lock.yaml

テスト環境で API サーバーを起動する方法も取れたのですが、APIの実装に web のテストが依存してしまうのを避けるため、API は msw でモックサーバーを立てて、テストを実行できるようにしました。

web パッケージにテスト環境とテストコードを追加

---

packages/web/app/routes/feed[.xml].tsx

rssにimageを追加しました
メモ: entryのmetaの情報の整形の実装とfeecの情報の整形の実装がだいぶ似てるので共通化しても良さそう

feat(rss): add og image

---

.github/workflows/ci.yml

Re: #95
---
無駄をyasunoriするのに成功した気がします（次に package/clojure-yasunori を変えたときに実際のテストはできると思います）
手元ではちゃんと動いてるのは確認できました
- main更新前（packages/clojure-yasunoriに差分がある） -> clojure-yasunoriのジョブが起動される
https://github.com/conao3/awesome-yasunori/actions/runs/11284276463
- main更新後（packages/clojure-yasunoriに差分がない） -> clojure-yasunoriのジョブが起動されない
https://github.com/conao3/awesome-yasunori/actions/runs/11284330435

Re: runs only when related file is changed

---

.github/workflows/ci.yml

CIで不要なビルドをスキップするためのCheck Changesジョブ f5af8a6e9014224cf3ffb1da29518220a21afc2b にパターンが追加しやすくなるように、[paths-filter](https://github.com/dorny/paths-filter)アクションを使います。
ちなみに、すべてのパッケージをNixでビルドできればこの差分チェック自体が不要です(#110)。

差分チェックにpaths-filterを使う

---

.github/workflows/cljs-breakout.yml
.gitignore
packages/cljs-yasunori-block/.dir-locals.el
packages/cljs-yasunori-block/.gitignore
packages/cljs-yasunori-block/Makefile
packages/cljs-yasunori-block/README.md
packages/cljs-yasunori-block/deps.edn
packages/cljs-yasunori-block/dev.cljs.edn
packages/cljs-yasunori-block/resources/public/index.html
packages/cljs-yasunori-block/src/yasunori_block/app.cljs
packages/cljs-yasunori-block/src/yasunori_block/core.cljs
packages/cljs-yasunori-block/wrangler.toml

ClojureScript yasunori block

---

packages/web/app/root.tsx

スマホ環境で段ずれが発生してしまうことを確認したので、悩んだ結果、ヘッダーからRSSアイコンを削除することにしました。
削除前
削除後
なお、削除する判断に至った理由は次の通りです。
- `/stats` へのリンクをサイドナビなどに入れてみたが、エントリー一覧の中に、ひとつだけ他のページへのナビゲーションがあるのは違和感が強いため
- RSSが必要な人はHTMLソースを見て調べることに慣れているため
- ヘッダー左にメニューをつけるほどでもないため

RSSアイコンをヘッダーから削除

---

packages/web/app/root.tsx
packages/web/app/routes/_index/loader.test.ts
packages/web/app/routes/_index/loader.ts
packages/web/app/shared/fetch-awesome-yasunori.ts

Implement yasunorization

---

packages/api/src/index.test.ts
packages/api/src/index.ts

Close #150
下記の結果が得られるようになりました。
```sh
$ curl -X POST https://9da22547.yasunori-apis.pages.dev/awesome/from-slack-text -H 'Content-Type: text/plain' \
--data "tomoya
21:06
えっ、yasunori 知らないの?
↑
yasuhara"
[[yasunori]]
id = 2
title = "えっ、yasunori 知らないの?"
date = "2024-11-02"
at = "vim-jp #times-yasunori"
senpan = "tomoya"
content = """
えっ、yasunori 知らないの?
↑
yasuhara
"""
meta = """
"""
```

Add POST /awesome/from-slack-text

---

packages/api/src/index.test.ts
packages/api/src/index.ts

body なしで、 POST /awesome/from-slack-text にリクエストしたら、下記のテンプレートを出力するようにしました。
```toml
[[yasunori]]
id = 76
title = ""
date = "2024-11-06"
at = "vim-jp #times-yasunori"
senpan = ""
content = """
"""
meta = """
"""
```

POST /awesome/from-slack-text で body がなければ空のテンプレートを返すようにする

---

packages/api/package.json
packages/api/src/client.ts
packages/web/app/shared/yasunori-api.ts
packages/web/package.json
pnpm-lock.yaml

- hono clientをapi側に移しました
- hono をwebの依存関係から削除しました

hono clientをapiに移す

---

.github/workflows/ci.yml
packages/mcp/package.json
pnpm-lock.yaml

pkg.pr.newを使ってmcpをpublishすることにしました
加えて、lintのactions名も修正しておきました
pkg-pr-newのコメントにあるpacckage名からinstallできるようになります
```
pnpx  https://pkg.pr.new/times-yasunori/awesome-yasunori/mcp@172
```

feat(mcp): publish mcp on pkg.pr.new

---

.npmrc
flake.lock
nix/overlays.nix
nix/packages/default.nix
nix/packages/mcp/default.nix
package.json
packages/api/package.json
packages/image-generator/package.json
packages/web/package.json

- yasunori mcp serverをNixでパッケージングできるようにしました。
- pnpm workspaceを扱うにあたって必要なnixpkgsの機能を使うため、flake.lockを更新しました。
- これに伴って従来のnodeおよびpnpmのビルドが通らなくなったので更新しました。
This pull request includes several updates to the Node.js and pnpm versions across multiple configuration files, as well as the addition of a new package configuration for `yasunori-mcp`.
* Updated Node.js version from `20.17.0` to `20.19.0` in `.npmrc` and `nix/overlays.nix`. [[1]](diffhunk://#diff-e813096d69c49812e40e00be9ac8fa14d77f0ec1f97ab4c45cb096b3bedd35deL2-R2) [[2]](diffhunk://#diff-2ad718dbee070e69c53ba853ab0fb35c49816b00d91c07bab2c024acd81a6409L6-R21)
* Updated pnpm version from `9.11.0` to `9.15.9` in `nix/overlays.nix`, `package.json`, `packages/api/package.json`, `packages/image-generator/package.json`, and …

add yasunori mcp nix

---

.github/workflows/ci.yml
.gitignore
flake.lock
flake.nix
nix/packages/mcp/default.nix
nix/shells/default.nix

Nix Packageを追加した際にCI上でのチェックが追加されておらず、マージ前のテスト漏れが発生した。
Nix式の側でチェック項目を定義して、チェックに漏れが発生しないようにする。
また、コミット時点でチェックが走るようにする事で、フォーマット漏れやNix式の破壊などに気付けるようにする。
- git-hooks.nixを導入して、pre-commit hookで `nix flake check` を実行できるようにした
- `perSystem.check` を定義して、 `nix/` 以下のderivationをcheckできるようにした
- CIのビルドフェーズを削除して、checkのフェーズに統合した

improve nix flake check

---

packages/api/src/index.test.ts
packages/api/src/index.ts

Introduce a new GET endpoint `/awesome/list` that returns a list of all awesome entries, containing only their `id` and `title`.
Add corresponding tests to ensure the endpoint returns a 200 status code and the expected JSON structure.
マージ後、デプロイお願いします！@tomoya

feat(api): add /awesome/list endpoint

---

nix/packages/mcp/default.nix

fix: hash of pnpm used in yasunori-mcp

---

packages/api/.npmrc
packages/image-generator/.npmrc
packages/mcp/package.json
packages/mcp/src/search.test.ts
packages/mcp/src/search.ts
packages/mcp/tsdown.config.ts
pnpm-lock.yaml

This PR fixes issues with the MCP server's search functionality and adds comprehensive Japanese text search support.
- **Fixed Orama document ID type mismatch**: Changed document IDs from `number` to `string` type to match Orama's internal requirements
- **Added Japanese text search support**: Integrated `wakachigaki` tokenizer for proper Japanese word segmentation
- **Enhanced search configuration**: Updated Orama tokenizer settings to properly handle Japanese text
- **Comprehensive test coverage**: Added tests for Japanese text search functionality
- **Dependency management**: Moved runtime dependencies to correct section and updated build configuration
- ✅ Japanese text queries like "テスト" and "プログラミング" now work correctly
- ✅ Proper word segmentation for Japanese text using wakachigaki …

Fix search functionality and add Japanese text search support
